### ISSUE TITLE
Camel case models

### ISSUE THREAD

**Issue by fcouceiro** [clubeprogramacao/Website#4]
Some models have camel case attributes. Like in the Event case:

> {
>   "success": true,
>   "data": {
>     "title": "Event test",
>     "description": "This event came from the API",
>     "eventDate": "2016-07-29T15:39:26.092Z",
>     "external": "1",
>     "updated_at": "2016-07-29 15:39:38",
>     "created_at": "2016-07-29 15:39:38",
>     "id": 1
>   }
> }

And it's a bit difficult to POST these methods because if you provide the `event_date` it stills throws the error `"The event date field is required."`.

**Comment by rscmendes** [comment]
Fixed on commit 92e43f8216ddc930fa6ad1c3c0858e911479859b. All model attributes are now snake_case.
